# Generated by Django 2.1.5 on 2019-02-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poked_users', models.ManyToManyField(through='loginRegistration.Pokes', to='loginRegistration.Users')),
            ],
        ),
        migrations.AddField(
            model_name='pokes',
            name='poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokers', to='loginRegistration.Users'),
        ),
        migrations.AddField(
            model_name='pokes',
            name='poker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loginRegistration.Users'),
        ),
    ]
